version: "2.0"

services:
  api:
    build: ./api/
    image: todo_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:11.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  front:
    build: ./front/
    image: todo_front
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./front:/front
    depends_on:
      - api
    command: npm start

volumes:
  postgres_data:
